CREATE DATABASE gestao_financeira;

CREATE TABLE tb_user
(ID_USUARIO INT PRIMARY KEY,
FULL_NAME VARCHAR(200),
EMAIL VARCHAR(200),
PASSWORD VARCHAR(50));

CREATE TABLE tb_income 
(ID_INCOME INT PRIMARY KEY,
TYPE_OF_INCOME VARCHAR(100),
ENTRY_CATEGORY VARCHAR(100),
INCOME_VALUE FLOAT);

CREATE TABLE tb_expense 
(ID_EXPENSE INT PRIMARY KEY,
EXPENSE_TYPE VARCHAR(200),
EXPANSE_NAME VARCHAR(200),
EXPENSE_VALUE FLOAT, 
EXPENSE_STATUS VARCHAR(50),
DUE_DATE DATE);

CREATE TABLE tb_financial_goal 
(FINANCIAL_GOAL TEXT);